import type { Metadata } from 'next'
import { Inter, Source_Code_Pro } from 'next/font/google'
import './globals.css'
import Header from '@/Components/Header'

const inter = Inter({ subsets: ['latin'] })
const sourceCodePro = Source_Code_Pro({ subsets: [] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.className} bg-[#0f0f23]`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
